services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  dotnet-notification-service:
    build:
      context: ./dotnet-notification-service
      dockerfile: ../Dockerfile
    ports:
      - "5143:5143"